services:
  postgres:
    image: postgres:15.3
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./.db:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    env_file:
      - .env

  redis:
    image: redis:7.2
    container_name: redis_queue
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
